#!/bin/sh

set -e

while getopts ":h" opt; do
  case $opt in
    h)
      echo "A tool for simplifying the install of newer Linux kernels on Ubuntu systems."
      echo
      echo "Usage: sudo ./automagical-kernel-install"
      echo
      echo "Getting help:"
      echo "  -h     Print basic options available"
      echo
      echo "Flags available:"
      echo "  -r     Include RC releases as potential upgrade targets"
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG. Aborting" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument. Aborting." >&2
      exit 1
      ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: this program requires superuser privileges. Aborting."
  exit 1
fi

URL="http://kernel.ubuntu.com/~kernel-ppa/mainline/"

get_versions () {
  URL="${1}"
  wget -q -O - "${URL}" | grep "href=\"v" | cut -d \" -f8
}

user_warning() {
  WARNING_MESSAGE="${1}"

  echo "$WARNING_MESSAGE"

  read INPUT

  if [ "${INPUT}" != "y" ]; then
    echo "Aborting."
    exit 1
  fi
}

if [ "$(uname -i)" = "x86_64" ]; then
  ARCH="amd64"
else
  ARCH="i386"
fi

CURRENT_KERNEL="$(uname -r)"

if [ "${CURRENT_KERNEL##*-}" = "generic" ]; then
  TYPE="generic"
else
  TYPE="lowlatency"
fi

echo -n "Finding latest kernel .."

VERSION="$(get_versions "${URL}" | tail -n 1)"

user_warning ".. latest version is ${VERSION} for ${ARCH}. Proceed to download kernel? [y/n]"

TEMP_DIR="$(mktemp -d)" || exit 1
trap 'rm -rf "${TEMP_DIR}"' EXIT

DIRECTORY="${URL}${VERSION}"

wget -q -O - "${DIRECTORY}" |
grep -e "all.deb\|${TYPE}.*${ARCH}" |
cut -d \" -f8 |
while read LINK; do
  wget "${DIRECTORY}${LINK}" -P "${TEMP_DIR}"
done

user_warning "WARNING: Installing this kernel can break your system. Continue? [y/n]"

dpkg -i "${TEMP_DIR}"/*.deb

echo "Finished installing."

