#!/bin/sh

set -e

if [ "$(uname -i)" = "x86_64" ]; then
  ARCH="amd64"
else
  ARCH="i386"
fi

CURRENT_KERNEL="$(uname -r)"

if [ "${CURRENT_KERNEL##*-}" = "generic" ]; then
  TYPE="generic"
else
  TYPE="lowlatency"
fi

echo -n "Finding latest kernel .."

URL="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
HTML="$(wget -q -O - ${URL} | grep href | tail -n 1)"

VERSION="${HTML#*</td><td><a href=\"}"
VERSION="${VERSION%/\">*}"

echo ".. latest version is ${VERSION} for ${ARCH}. Continue? [y/n]"

read INPUT

if [ "${INPUT}" != "y" ]; then
  echo "Aborting."
  exit 1
fi

TEMP_DIR="$(mktemp -d)" || exit 1
trap 'rm -rf "${TEMP_DIR}"' EXIT

