#!/bin/sh

set -e

if [ "$(uname -i)" = "x86_64" ]; then
  ARCH="amd64"
else
  ARCH="i386"
fi

CURRENT_KERNEL="$(uname -r)"

if [ "${CURRENT_KERNEL##*-}" = "generic" ]; then
  TYPE="generic"
else
  TYPE="lowlatency"
fi
